// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/AI/chat/history": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取指定会话的历史消息列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话"
                ],
                "summary": "获取会话历史",
                "parameters": [
                    {
                        "description": "会话ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/session.ChatHistoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/session.ChatHistoryResponse"
                        }
                    }
                }
            }
        },
        "/AI/chat/send": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "在指定会话中发送用户问题，返回 AI 回答",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话"
                ],
                "summary": "向已有会话发送消息",
                "parameters": [
                    {
                        "description": "用户问题、模型类型与会话ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/session.ChatSendRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/session.ChatSendResponse"
                        }
                    }
                }
            }
        },
        "/AI/chat/send-new-session": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建新会话并发送用户问题，返回 AI 回答与新的会话ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话"
                ],
                "summary": "创建新会话并发送消息",
                "parameters": [
                    {
                        "description": "用户问题与模型类型",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/session.CreateSessionAndSendMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/session.CreateSessionAndSendMessageResponse"
                        }
                    }
                }
            }
        },
        "/AI/chat/send-stream": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "在指定会话中发送用户问题，以 SSE 流式返回 AI 回答",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "会话"
                ],
                "summary": "向已有会话流式发送消息",
                "parameters": [
                    {
                        "description": "用户问题、模型类型与会话ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/session.ChatSendRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE 数据流",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/AI/chat/send-stream-new-session": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建新会话并以 SSE 流式返回 AI 回答，数据流先返回 sessionId 再返回回答内容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "会话"
                ],
                "summary": "创建新会话并流式发送消息",
                "parameters": [
                    {
                        "description": "用户问题与模型类型",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/session.CreateSessionAndSendMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE 数据流",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/AI/chat/sessions": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "返回当前登录用户的所有会话",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话"
                ],
                "summary": "获取用户会话列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/session.GetUserSessionsResponse"
                        }
                    }
                }
            }
        },
        "/AI/chat/tts": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "提交文本创建语音合成任务，返回任务ID供轮询查询",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "语音合成"
                ],
                "summary": "创建TTS语音合成任务",
                "parameters": [
                    {
                        "description": "待合成文本",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/GopherAI_common_tts.TTSRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tts.TTSResponse"
                        }
                    }
                }
            }
        },
        "/AI/chat/tts/query": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过任务ID查询语音合成状态与结果URL",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "语音合成"
                ],
                "summary": "查询TTS任务结果",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "task_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tts.QueryTTSResponse"
                        }
                    }
                }
            }
        },
        "/file/upload": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "上传文本文件用于RAG检索（每个用户仅保留一个文件，上传新文件会替换旧文件）",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件"
                ],
                "summary": "上传RAG知识库文件",
                "parameters": [
                    {
                        "type": "file",
                        "description": "文本文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/file.UploadFileResponse"
                        }
                    }
                }
            }
        },
        "/image/recognize": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "上传一张图片，返回识别出的类别名称",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图像"
                ],
                "summary": "图像识别",
                "parameters": [
                    {
                        "type": "file",
                        "description": "待识别的图片文件",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/image.RecognizeImageResponse"
                        }
                    }
                }
            }
        },
        "/user/captcha": {
            "post": {
                "description": "向指定邮箱发送注册验证码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "发送邮箱验证码",
                "parameters": [
                    {
                        "description": "邮箱地址",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.CaptchaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.CaptchaResponse"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "使用账号密码登录，成功后返回 JWT Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.LoginResponse"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "使用邮箱+验证码+密码注册，注册成功直接返回 JWT Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.RegisterResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "GopherAI_common_tts.TTSRequest": {
            "type": "object",
            "properties": {
                "enable_subtitle": {
                    "type": "integer"
                },
                "format": {
                    "type": "string"
                },
                "lang": {
                    "type": "string"
                },
                "pitch": {
                    "type": "integer"
                },
                "speed": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                },
                "voice": {
                    "type": "integer"
                },
                "volume": {
                    "type": "integer"
                }
            }
        },
        "code.Code": {
            "type": "integer",
            "format": "int64",
            "enum": [
                1000,
                2001,
                2002,
                2003,
                2004,
                2005,
                2006,
                2007,
                2008,
                2009,
                2010,
                3001,
                4001,
                5001,
                5002,
                5003,
                6001
            ],
            "x-enum-varnames": [
                "CodeSuccess",
                "CodeInvalidParams",
                "CodeUserExist",
                "CodeUserNotExist",
                "CodeInvalidPassword",
                "CodeNotMatchPassword",
                "CodeInvalidToken",
                "CodeNotLogin",
                "CodeInvalidCaptcha",
                "CodeRecordNotFound",
                "CodeIllegalPassword",
                "CodeForbidden",
                "CodeServerBusy",
                "AIModelNotFind",
                "AIModelCannotOpen",
                "AIModelFail",
                "TTSFail"
            ]
        },
        "file.UploadFileResponse": {
            "type": "object",
            "properties": {
                "file_path": {
                    "type": "string"
                },
                "status_code": {
                    "$ref": "#/definitions/code.Code"
                },
                "status_msg": {
                    "type": "string"
                }
            }
        },
        "image.RecognizeImageResponse": {
            "type": "object",
            "properties": {
                "class_name": {
                    "description": "AI回答",
                    "type": "string"
                },
                "status_code": {
                    "$ref": "#/definitions/code.Code"
                },
                "status_msg": {
                    "type": "string"
                }
            }
        },
        "model.History": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "is_user": {
                    "type": "boolean"
                }
            }
        },
        "model.SessionInfo": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "sessionId": {
                    "type": "string"
                }
            }
        },
        "session.ChatHistoryRequest": {
            "type": "object",
            "required": [
                "sessionId"
            ],
            "properties": {
                "sessionId": {
                    "description": "当前会话ID",
                    "type": "string"
                }
            }
        },
        "session.ChatHistoryResponse": {
            "type": "object",
            "properties": {
                "history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.History"
                    }
                },
                "status_code": {
                    "$ref": "#/definitions/code.Code"
                },
                "status_msg": {
                    "type": "string"
                }
            }
        },
        "session.ChatSendRequest": {
            "type": "object",
            "required": [
                "modelType",
                "question",
                "sessionId"
            ],
            "properties": {
                "modelType": {
                    "description": "模型类型;",
                    "type": "string"
                },
                "question": {
                    "description": "用户问题;",
                    "type": "string"
                },
                "sessionId": {
                    "description": "当前会话ID",
                    "type": "string"
                }
            }
        },
        "session.ChatSendResponse": {
            "type": "object",
            "properties": {
                "Information": {
                    "description": "AI回答",
                    "type": "string"
                },
                "status_code": {
                    "$ref": "#/definitions/code.Code"
                },
                "status_msg": {
                    "type": "string"
                }
            }
        },
        "session.CreateSessionAndSendMessageRequest": {
            "type": "object",
            "required": [
                "modelType",
                "question"
            ],
            "properties": {
                "modelType": {
                    "description": "模型类型;",
                    "type": "string"
                },
                "question": {
                    "description": "用户问题;",
                    "type": "string"
                }
            }
        },
        "session.CreateSessionAndSendMessageResponse": {
            "type": "object",
            "properties": {
                "Information": {
                    "description": "AI回答",
                    "type": "string"
                },
                "sessionId": {
                    "description": "当前会话ID",
                    "type": "string"
                },
                "status_code": {
                    "$ref": "#/definitions/code.Code"
                },
                "status_msg": {
                    "type": "string"
                }
            }
        },
        "session.GetUserSessionsResponse": {
            "type": "object",
            "properties": {
                "sessions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SessionInfo"
                    }
                },
                "status_code": {
                    "$ref": "#/definitions/code.Code"
                },
                "status_msg": {
                    "type": "string"
                }
            }
        },
        "tts.QueryTTSResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "$ref": "#/definitions/code.Code"
                },
                "status_msg": {
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                },
                "task_result": {
                    "type": "string"
                },
                "task_status": {
                    "type": "string"
                }
            }
        },
        "tts.TTSResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "$ref": "#/definitions/code.Code"
                },
                "status_msg": {
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                }
            }
        },
        "user.CaptchaRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "user.CaptchaResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "$ref": "#/definitions/code.Code"
                },
                "status_msg": {
                    "type": "string"
                }
            }
        },
        "user.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "user.LoginResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "$ref": "#/definitions/code.Code"
                },
                "status_msg": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "user.RegisterRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "captcha": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "user.RegisterResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "$ref": "#/definitions/code.Code"
                },
                "status_msg": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9090",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "GopherAI API",
	Description:      "GopherAI AI 聊天后端接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
